# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Esteban Eduardo Hebel Neira MD MMSc
title: Biomedical Informatician / Clinical Radiologist
email: ehebel@gmail.com
website: ehebel.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ehebeln
github_username:  ehebel
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: estebanhebel
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: dbmi.hms.harvard.edu
  icon: fas fa-globe
  url: https://dbmi.hms.harvard.edu/people/esteban-hebel
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Esteban and I'm a clinical radiologist and biomedical informatician.
  My objective is to use my clinical imaging and informatics expertise developing health technologies to improve care for poor, urban and rural, communities at the local, regional and national level by supporting public health practice and policymaking.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: National Shared Health Record project
        # link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  minsal_cl/interoperabilidad
            icon: fab fa-github
            url: github.com/minsal_cl
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This project aimes to become the central Clinical Data Repository for the Chilean Healthcare System.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Professional Experience # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      2020 – Present&emsp;Chief Medical Information Officer, Department of Digital Health, Araucaria Sur Health Service, Temuco, Chile. 
      
      2017 – Present&emsp;Clinical Radiologist, Clinica Alemana Temuco, Temuco, Chile
      
      2020 – Present&emsp; Professor “Course: Introduction to Health Information Systems for clinicians and decision makers.” Center for Information Systems in Healthcare, CENS, Santiago, Chile.
      
      2020 – Present&emsp; Professor “Diploma: Clinical Informatics” School of Medicine, Pontificia Universidad Católica de Chile, Santiago, Chile
      
      2017 – 2020&emsp;Senior Health Informatics Advisor, Araucania Sur Health Service, Temuco, Chile.
      
      2014 – 2017&emsp;Radiology resident, Clinica Alemana Santiago, Santiago, Chile
      
      2012 – 2014 &emsp; Senior Clinical Informatician, Ministry of Health. Santiago, Chile.
      
      2012 – 2016 &emsp; Professor of “Hospital Information Systems” – Medical Informatics Master’s Program – Universidad de Chile, School of Medicina & School of Physics and Mathematics; Heidelberg University & Heidelberg Center for Latin America
      
      2010 – 2012 &emsp; Research Fellow, Clinical Informatics Research & Development, Partners Healthcare, Boston, MA.
      
      2011 – 2013 &emsp; Scientific reviewer for: 
     - Journal of Journal of the American Medical Informatics Association (JAMIA)
     - International Journal of Medical Informatics (IJMI)
     - Applied Clinical Informatics (ACI)

      2008 – 2009 &emsp; Health Informatics Advisor, developing and implementing solutions for the public health sector in a regional scale. 
     - Emergency Care Physician, Vilcún Hospital, Araucania Sur Health Service, Temuco, Chile.
      
      2008 &emsp;General Physician, Fresia Hospital, Reloncaví Health Service, Fresia, Chile.
      
      2007 - 2008 &emsp;Epidemiology Analyst, Araucanía Sur Health Service, Temuco, Chile.

    # content:
    #   - layout: left
    #     title: Araucanía Sur Health Service
    #     link: www.araucaniasur.cl
    #     # link_text: boringcompany.com
    #     sub_title: Digital Health Department Chief
    #     caption: July 2020 - Present
    #     quote: >
    #       Bringing the Digital Transformation to Healthcare, one step at a time.
    #     description: | # this will include new lines to allow paragraphs
    #       The seemingly infinite path to healthcare digitalization.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Universidad de La Frontera
        sub_title: Temuco, Chile
        caption: 2001 - 2007
        sub_title: Medical Doctor
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs


      - layout: left
        border: weak
        title: Universidad de La Frontera
        sub_title: Temuco, Chile
        caption: 2001 - 2005
        sub_title: Bachelor Degree in Medicine
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs

      - layout: left
        border: weak
        title: Harvard University
        sub_title: Boston, MA
        caption: 2010 - 2012
        sub_title: Master of Medical Sciencies in Biomedical Informatics
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs

      - layout: left
        title: Universidad del Desarrollo
        sub_title: Santiago, Chile
        caption: 2014 - 2017
        sub_title: Clinical Radiology Residency
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: Projects under current supervision
    layout: text
    content: | # this will include new lines to allow paragraphs
      2022&nbsp;&nbsp;&nbsp;&nbsp;Region wide Adverse Events Surveillance System – Clinical Quality Department

      2021&nbsp;&nbsp;&nbsp;&nbsp;Integrated Oncology Information System – Regional Cancer Surveillance Group

      2020 – Present&emsp;Deployment & maintenance of HL7 FHIR Clinical Data Repository (Roche Diagnostics)

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Computing:** STATA; Transact-SQL; Project REDCap; OracleBI; R; Pentaho Report Designer;Pentaho Data Integration; JasperSoft, iReport; Python.

      **Languages:** Fluent in Spanish, English and German.
    
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      Hebel E.; Schiappacasse G. Involvement of the digestive tube due to endometriosis: an important manifestation to remember. Gastroenterol. latinoam 2016; Vol 27, Nº 2: 101-105

      Rinaldi S, Medina C, Hebel E., Silva C, Chong G. Radiological case for diagnostic challenge. Revista Chilena de Radiología (Rev. chil. radiol. vol.22 no.1, 2016)

      Einbinder J, Hebel E, Wright A, Panzenhagen M, Middleton B. The Number Needed to Remind: A Measure for Assessing CDS Effectiveness. AMIA Annu Symp Proc. 2014;2014:506–15.

      Hebel Esteban, Middleton Blackford, Shubina Maria, Turchin Alexander: “Bridging the chasm: Effect of health information exchange on volume of laboratory testing”, Arch. Intern. Med. 2012; 172(6):517–519.

      Marucich C,  Borel V,  Barrios J,  Hebel  Esteban, Cea X, Bustos L:  “Mortality Analysis Associated with Tuberculosis in Temuco City, Between 1998 and 2004”, REMS. Nov 2005, 1(2): pp 18 - 25. 
      
      Hebel Esteban: “The Tobacco Pandemic”, Pediatría al día, Sept/Oct 2006: 22(4): pp 59-60.
      
      Hebel Esteban, Ibieta Felipe, Constance Marucich: “Global Youth Tobacco Survey Applied in Melipeuco, 9th Region”, Pediatría al día, Nov/Dec 2007: 23(5): pp 59-60.
      
      Hebel Esteban., Bustos P., Rodriguez B., Monsalves J.: “Incidence of Respiratory Diseases in the Amanecer Family Health Center in Temuco between April and September, 2004”, REMS Jan 2006; 2(2).
      
      Giselle Fétis N., Luis Bustos M.,Fernando Lanas Z., Bernardita Baeza W., Juan Contreras R., Esteban Hebel N., Constance Marucich: “B. Factors Associated with the Use of Contraceptive Methods by High School Students in Temuco”, REV CHIL OBSTET GINECOL 2008; 73(6): pp. 362 – 369.
      
      Neira R., Pérez G., Hebel E., Moya K., Sanhueza L. Sociodemographic Profile of the Older Adults in the Araucanía – First Part. Rev Med Sur (ISSN 0716 - 6222) – 2008; 30(1-2): pp. 86 – 95.
      
      Valdes P., Bustos L., Marucich C., Fulgeri C., Hebel E.: “Descriptive Analysis of the Female Profile at a Family Planning Clinic, Secondary Level”, Rev Med Sur (ISSN 0716 - 6222) – Accepted & Publication in Process.

  - title: Working Papers Presented at Seminars
    layout: text
    content: | # this will include new lines to allow paragraphs
      Hebel E., Araucanía Sur Health Service Laboratory Interoperability Project. ExpoHospital 2019.
      
      Ortiz J., Hebel E., Silva C.: Validation of Natural Language Processing Tools for Identification Of Pulmonary Embolism Between 2013-2014. RSNA 2016
      
      Labra A., Franz G., Zieghlerh W., Hebel E., Schiappacasse G., Schultz M., Soffia P.; Fusion prostate biopsies. Does it increase performance to screen for prostate cancer? - Congreso Chileno De Radiología 2016
      
      Guilloff S., Hebel E., Niedmann J.: Evaluation of lavage of calcific tendinitis by interventional ultrasound - Congreso Chileno De Radiología 2016 
      
      Hebel E., Ortiz J., Silva C. Use of Natural Language Processing for the Identification of Pulmonary Thromboembolism in Clínica Alemana de Santiago between 2013-2014 - 10º Congreso ALAT 2016
      
      Labra A.; E. Hebel; G. Schiappacasse; F. Zúñiga Is the Calculated ADC Value of the 3t Multiparametric Magnetic Resonance Imaging (MPMR) Associated With the Gleason Grade of the Lesions Evaluated in Pathological Anatomy? Congreso de la Sociedad Chilena de Radiología 2015.
      
      Labra A.; Hebel E.; G. Schiappacasse; F. Zúñiga; M. Schulz. Anatomical-Radiological Concordance Between 3T Multiparametric Magnetic Resonance Imaging With Surface Coil And Radical Prostatectomy During The Years 2014-2015. Congreso de la Sociedad Chilena de Radiología 2015.
      
      Labra A.; Hebel E.; F. Zúñiga; G. Schiappacasse; G. Chong. Detection of Secondary Prostate Cancer Lesions with a Prostate Specific Membrane Antigen (PSMA) Ligand in Positron Emission Tomography Fused with Computed Tomography (PET-CT). Congreso de la Sociedad Chilena de Radiología 2015.
      
      Labra A.; Zúñiga F.; Hebel E.; G. Schiappacasse. Detection of Prostate Cancer by 3t Multiparametric Resonance in Patients with a Previous Negative Biopsy. Pirads Utility. Congreso de la Sociedad Chilena de Radiología 2015.
      
      Labra A.; Hebel E.; F. Zúñiga; Anatomical-Radiological Concordance Study Between 3t Multiparametric Magnetic Resonance Imaging with Surface Coil And Radical Prostatectomy During The Year 2014-2015 - Congreso Chileno De Urología 2015
      
      Labra A, Hebel E; Zuñiga F; Schiappacasse G; Chong G. Prostate Specific Membrane Antigen (PSMA) Ligand Used in Positron Emission Tomography Fused with Computed Tomography (PET-CT) in Detection of Secondary Prostate Cancer Lesions. - Congreso Chileno De Urología 2015
      
      Hebel, E.: The Number Needed to Remind: a Measure for Assessing CDS Effectiveness. AMIA Annual Meeting 2014.
      
      Hebel Esteban: “Prevalence Study on Sexual Initiation of High School Adolescents in Urban Areas of Temuco”. Document presented at XXVI National Medical Students Congress. Santiago, Chile. Year 2003.
      
      Hebel Esteban., Bustos P., Rodriguez B., Monsalves J.: “Incidence of Respiratory Diseases in the Amanecer Family Health Center in Temuco between April and September, 2004”. Document presented at XXXIX Chilean Congress of Respiratory Diseases. Chile. Year 2006. 
      
      Hebel Esteban., Bustos P., Cea X.: “Relation between the Exposure to Particulate Material and Consults for Respiratory Diseases in the Amanecer Family Health Center in Temuco between April and September, 2004”. Document presented at XXXIX Chilean Congress of Respiratory Diseases. Chile. Year 2006. 
      
      Hebel Esteban. Bustos P. Cea X.: “Relation between the Exposure to Particulate Material and Hospital Admissions for Respiratory and Cardiovascular Diseases at Dr. Henríquez Hospital in Temuco in 2004”. Document presented at XXXIX Chilean Congress of Respiratory Diseases. Chile. Year 2006. 
      
      Gorena M., Ibieta F. Zambrano P. Hebel E.: “Upper Urinary Tract Cancer between 2001 and 2006 in the Hernán Henríquez Hospital, Temuco. Eight case studies and literature review”. Document presented at the 16th Cautín Medical Society Scientific Meeting. Chile. November 15-16, 2007.

#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
